### ISSUE TITLE
Rethink Results structure

### ISSUE THREAD

**Issue by mkolarek** [zalando/expan#66] opened 2017-02-03 16:07 UTC
The goal of the current implementation of the Results structure is to enable the user to easily concatenate the results of multiple analyses (say delta() + sga()).
This functionality hasn't been used much, so it would be a good idea to rethink the Results structure and maybe aim to simplify it.

**Comment by gbordyugov** [comment] 2017-02-27 12:48
I see as one of potential improvements the possibility of eliminating the intermediate data frame objects (produced by `*_to_dataframe_*()` functions)

**Comment by gbordyugov** [comment] 2017-04-05 09:18
duplicate of https://github.com/zalando/expan/issues/82

**Closed as completed by gbordyugov** 2017-04-05 09:18 UTC
