### ISSUE TITLE
SGA Percentile Issue

### ISSUE THREAD

**Issue by louisryan** [zalando/expan#178] opened 2018-01-08 18:13 UTC
Hi there, 

I'm testing the new SGA functionality and have noticed that the percentile does not return what I expected. On Version 0.66, when I run `exp.sga({'dimension': bbin})`, I get the following percentiles:

![screen shot 2018-01-08 at 18 09 57](https://user-images.githubusercontent.com/1322755/34685170-6fada5f6-f49f-11e7-8d9f-91ad87385b93.png)

As you can see, the two percentiles are 0.8333 and 99.1667, instead of 2.75 and 97.5. Is this expected behaviour? And if so, would you be able to explain the rationale?

Many thanks,
Louis

**Comment by shansfolder** [comment] 2018-01-09 09:53
hi @louisryan, thanks a lot for spotting this. There is actually a reason, we implicitly made a [multiple testing correction](https://en.wikipedia.org/wiki/Multiple_comparisons_problem), so the alpha value are changed. 
But we understand that this result structure is very confusing now, we will make the method without multiple test correction by default, and let you know.

**Comment by louisryan** [comment] 2018-01-09 11:34
Interesting! So to be clear, the interval values(in this case `0.066114`/`0.19084`) are not valid? Or is it simply that the percentiles are mislabeled?

**Comment by shansfolder** [comment] 2018-01-09 12:57
@louisryan yep the interval values are valid. 

Due to multiple testing problem, to make a [2.5, 97.5] percentile more statistically valid, you will need a stricter alpha. So the method corrects the interval to become [0.83, 99,16]. Thus the interval values you see is actually "more" valid.

The problem is that it is confusing without explanation. We will think about it and update the method signature.

**Comment by shansfolder** [comment] 2018-01-12 19:08
hello @louisryan, thanks to Darya, now we add a flag ```multi_test_correction``` to both ```sga()``` and ```delta()```, which by default is ```False```. The latest Expan version is v0.6.10.

If you wish to perform the correction, you can set the parameter to be ```true```, and then it will lead to the behaviour you posted in this issue.

Documentation is also updated. We now have a section of what is multiple testing problem [here](http://expan.readthedocs.io/en/latest/glossary.html#multiple-testing-problem) and the new method signatures [here](http://expan.readthedocs.io/en/latest/tutorial.html#now-we-can-start-analysing).

**Comment by louisryan** [comment] 2018-01-16 08:50
Wow, great work! 🙂 I'll be sure to test it out this week

**Comment by daryadedik** [comment] 2018-02-06 10:24
Can we close this issues?

**Comment by shansfolder** [comment] 2018-02-06 13:04
Implemented.

**Closed as completed by shansfolder** 2018-02-06 13:04 UTC
Labels: bug, documentation
